### ISSUE TITLE
panic running bridge marker: out of bounds

### ISSUE THREAD

**Issue by yeya24** [kubevirt/bridge-marker#45]
```
❯ klo bridge-marker-rmsxv
E0119 07:31:28.783950       1 runtime.go:78] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
goroutine 1 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x13ea5a0, 0xc00002c960)
	/home/prow/go/src/github.com/kubevirt/bridge-marker/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/prow/go/src/github.com/kubevirt/bridge-marker/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x13ea5a0, 0xc00002c960)
	/home/prow/go/src/github.com/kubevirt/bridge-marker/build/_output/bin/go/src/runtime/panic.go:679 +0x1b2
github.com/vishvananda/netlink.parseIptunData(0x166b120, 0xc00013a000, 0xc000104800, 0xd, 0x10)
	/home/prow/go/src/github.com/kubevirt/bridge-marker/vendor/github.com/vishvananda/netlink/link_linux.go:2580 +0x2d7
github.com/vishvananda/netlink.LinkDeserialize(0x0, 0xc000250838, 0x594, 0x258c, 0x166b4e0, 0xc000141b80, 0x0, 0x0)
	/home/prow/go/src/github.com/kubevirt/bridge-marker/vendor/github.com/vishvananda/netlink/link_linux.go:1608 +0x148c
github.com/vishvananda/netlink.(*Handle).LinkList(0x2054e60, 0x7e01, 0x0, 0x166d7e0, 0xc000310c00, 0x166d7e0)
	/home/prow/go/src/github.com/kubevirt/bridge-marker/vendor/github.com/vishvananda/netlink/link_linux.go:1813 +0x2c6
github.com/vishvananda/netlink.LinkList(...)
	/home/prow/go/src/github.com/kubevirt/bridge-marker/vendor/github.com/vishvananda/netlink/link_linux.go:1791
github.com/kubevirt/bridge-marker/pkg/marker.getAvailableResources(0x15, 0xc000022c60, 0x203000)
	/home/prow/go/src/github.com/kubevirt/bridge-marker/pkg/marker/marker.go:63 +0x40
github.com/kubevirt/bridge-marker/pkg/marker.Update(0x7fffeecd776e, 0xc, 0xc00055ff10, 0xc0003a6ea0, 0xc000022c01)
	/home/prow/go/src/github.com/kubevirt/bridge-marker/pkg/marker/marker.go:97 +0x37
main.main.func1()
	/home/prow/go/src/github.com/kubevirt/bridge-marker/cmd/marker/main.go:60 +0xea
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00038df30)
	/home/prow/go/src/github.com/kubevirt/bridge-marker/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00055ff30, 0x1663a80, 0xc0003a6e70, 0x1, 0xc000046b40)
	/home/prow/go/src/github.com/kubevirt/bridge-marker/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00038df30, 0xdf8475800, 0x3ff3333333333333, 0x1, 0xc000046b40)
	/home/prow/go/src/github.com/kubevirt/bridge-marker/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xaa
main.main()
	/home/prow/go/src/github.com/kubevirt/bridge-marker/cmd/marker/main.go:44 +0x2ba
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0
```

Looks like the panic is raised from `github.com/vishvananda/netlink.parseIptunData(0x166b120, 0xc00013a000, 0xc000104800, 0xd, 0x10)`

**Comment by phoracek** [comment]
Thanks for reporting this @yeya24. This seems to be resolved via https://github.com/vishvananda/netlink/pull/549. I will update the dependency, so we consume this fix.

**Comment by yeya24** [comment]
Fixed by the latest image. Thanks!
